name: CI - Portfolio-Service
on: [push]
jobs:
  docker_build:
    runs-on: self-hosted
    steps:
       - uses: actions/checkout@v6
       - name: List files
         run: ls -l
       - name: Build image
         run: make docker-build

  eks-deploy:
    needs: docker_build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - uses: actions/checkout@v6
        with:
          repository: sh-devops-itrn-2/wmp-helm-v1
          path: helm
      - name: Helm Deploy
        run: make eks-deploy
      
